[package]
name = "cfdp-core"
version = "0.1.0"
edition = "2021"

[features]
uart = ["tokio-serial"]


[dependencies]
async-trait = "~0.1"
camino = {version = "~1.1", features=["serde1"]}
chrono = {version = "~0.4", default-features=false, features=["std"]}
interprocess = { version = "~1.2", features = ["tokio_support"] }
log = '~0.4'
num-derive = "0.3"
num-traits = "0.2"
pathdiff = "~0.2"
tempfile = "~3.3"
thiserror = "~1.0"
timer = "~0.2"
tokio = { version = "1", features = ["full"] }
tokio-serial = { version = "~5.4", optional = true }
tokio-util = { version = "0.7", default-features=false, features = ["rt", "compat"] }

[dev-dependencies]
signal-hook = "~0.3"
rstest = "0.15.0"
dirs = "~4.0"
