[package]
name = "cfdp-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
pathdiff = "~0.2"
tempfile = "~3.3"

[dev-dependencies]
rstest = "0.15.0"