[package]
name = "cfdp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "~0.5"
num-derive = "0.3"
num-traits = "0.2"
pathdiff = "~0.2"
tempfile = "~3.3"
timer = "~0.2"
time  = "~0.1"

[dev-dependencies]
rstest = "0.15.0"