[package]
name = "cfdp-core"
version = "0.1.0"
edition = "2021"

[features]
uart = ["serialport"]


[dependencies]
camino = {version = "~1.1", features=["serde1"]}
chrono = {version = "~0.4", default-features=false, features=["std"]}
crossbeam-channel = "~0.5"
interprocess = "~1.1"
itertools = "~0.10"
log = '~0.4'
num-derive = "0.3"
num-traits = "0.2"
pathdiff = "~0.2"
serialport = { version = "~4.2", optional = true }
signal-hook = "~0.3"
tempfile = "~3.3"
timer = "~0.2"

[dev-dependencies]
rstest = "0.15.0"
dirs = "~4.0"